language: ruby
dist: trusty
rvm:
  - 2.4.1
env:
  - DB=postgresql
bundler_args: "--without production"
cache: bundler
addons:
  chrome: stable
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
script:
  - bin/yarn install
  - RAILS_ENV=test bin/rails db:migrate
  - bin/rails test
  - bin/rails test:system
