version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: my-study
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: my-study
          POSTGRES_DB: my_study
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - my-study-bundle-v2-{{ checksum "Gemfile.lock" }}
            - my-study-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: my-study-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - my-study-yarn-{{ checksum "yarn.lock" }}
            - my-study-yarn-

      - run:
          name: Yarn Install
          command: yarn install

      # Store yarn / webpacker cache
      - save_cache:
          key: my-study-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - type: shell
        command: bin/rails test || bin/rails test:system

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
