version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.4-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: my-study
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: my-study
          POSTGRES_DB: my-study_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Install cmake
          command: sudo apt-get install -y cmake

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - type: shell
        command: bin/rails test:all

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
